app: # Environment variables (pom.xml)
  name: ${project.name}
  version: ${project.version}

server:
  port: 8080

api:
  prefix: ""
  cors:
    allowed-origins: "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers: "*"

websocket:
  path: "/ws"
  allowed-origins: "*"

spring:
  datasource:
    url: jdbc:mariadb://119.59.100.53:3306/mechat
    username: alltime_mechat
    password: iW~e0752p
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # จำนวน connection สูงสุด
      minimum-idle: 10 # จำนวน connection ต่ำสุด
      idle-timeout: 30000 # จำนวนเวลาที่ connection จะถูกปิดเมื่อไม่มีการใช้งาน
      connection-timeout: 30000 # จำนวนเวลาที่ connection จะถูกปิดเมื่อไม่สามารถเชื่อมต่อได้
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update # จัดการการสร้าง schema อัตโนมัติ (update, create, create-drop, validate)
    show-sql: true # แสดง SQL queries ที่ Hibernate สร้างขึ้น