app: # Environment variables (pom.xml)
  name: ${project.name}
  version: ${project.version}

server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    location: file:./application.yml
  datasource:
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: ${DB_PLATFORM}